env:
  global:
     - REPO_DIR="Python-software"
     - BUILD_COMMIT=master
     - PLAT=x86_64
     - UNICODE_WIDTH=32
     - NP_BUILD_DEP="numpy==1.8.1"
     - NP_TEST_DEP="numpy==1.8.1"
     - CYTHON_DEP="cython>=0.29.5"
     - PANDAS_TEST_DEP="pandas==0.20.0"
     - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
     - DAILY_COMMIT=master
     - secure: GvBPjG1wglLiG3lpg8aNVKUwSeMXmgLS+ul14fdAd6rFi5E0tRQ/fidnOKWuD8jPHs9TTU7onbeGdW5soZtMfX2UleHKBI/6Wwk5kMLbxAbUO/5kOHxf8AnBaikz0Bd9Hjz2IrsQavPJDNYL+KXFveLOpfN2cc/Ae9HJ+1y33jEuNrhr7swGcHyWs1QOZiSGDRyue6FVH56A64SNDivtbOQ6DSoD7RgqBpRtdJPJvNzi6stcSyZys5dctpO0smWOAmO6+bymlZLuxe3ZBcbREq1XSQ1MOIyses/oh9mp+5rgw3V6jFhReZL/gwEpRAKmhd5W1VFoya7eu8ch2Q8zhUYbKvvQafx2NZnDPn5r9rIybloy3g3D6wqG1YNOyqhAbGTESKKKeJo39N/SIcmT4R1GD1R6cyFgZtZt49qm2Pi12zjGHBqRiTFrrxG7laOyf6xwf+5evOthy/ZYo03+/kdY/+54uiog0UPkOKNZxyCAtrL8+t1N/9AuoeL6s8XIFx/y7KCWlT84Wx7xtOgspebjL102bI8JM1f5AQ0yANtThxwPYeDwSNhnCXDhmz+Hwl3oXPE63//nxATT1Y4ZWdrmOJwG7UDLu2dZV4WOMwFZL49EBNKkgsIlZBIR90FMlEz1A2cdnVCqj3h+YKgCFkz7ARg98Ftfr6l4bDXoHfo=

language: python
python: 3.5
sudo: required
dist: trusty
services: docker
matrix:
  exclude:
  - python: 3.5
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - NP_BUILD_DEP=numpy==1.9.3
    - NP_TEST_DEP=numpy==1.9.3
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - PLAT=i686
    - NP_BUILD_DEP=numpy==1.9.3
    - NP_TEST_DEP=numpy==1.9.3
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.11.3
    - NP_TEST_DEP=numpy==1.11.3
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - PLAT=i686
    - NP_BUILD_DEP=numpy==1.11.3
    - NP_TEST_DEP=numpy==1.11.3
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.16.1
    - NP_TEST_DEP=numpy==1.16.1
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - PLAT=i686
    - NP_BUILD_DEP=numpy==1.16.1
    - NP_TEST_DEP=numpy==1.16.1
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.5
    - NP_BUILD_DEP=numpy==1.9.3
    - NP_TEST_DEP=numpy==1.9.3
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.11.3
    - NP_TEST_DEP=numpy==1.11.3
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.15.0
    - NP_TEST_DEP=numpy==1.15.0
before_install:
- if [ "$TRAVIS_BRANCH" == "daily" ]; then CONTAINER="pre-release"; BUILD_COMMIT=${DAILY_COMMIT:-$BUILD_COMMIT};
  else CONTAINER=wheels; UPLOAD_ARGS="--no-update-index"; fi
- BUILD_DEPENDS="$CYTHON_DEP $NP_BUILD_DEP"
- TEST_DEPENDS="$CYTHON_DEP $NP_BUILD_DEP scipy nose mpmath regreg pyinter pandas sklearn"
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
after_success:
- pip install wheelhouse-uploader
- python -m wheelhouse_uploader upload --local-folder ${TRAVIS_BUILD_DIR}/wheelhouse/
  $UPLOAD_ARGS $CONTAINER
